export const jobIndustrySpecializationMap: Record<string, string[]> = {
  'Construction and Maintenance': [
    'Carpenter',
    'Electrician',
    'Plumber',
    'Mason',
    'Welder',
    'HVAC Technician',
    'Painter',
    'Heavy Equipment Operator',
  ],
  'Manufacturing and Production': [
    'Assembly Line Worker',
    'Machinist',
    'Fabricator',
    'Quality Control Inspector',
    'Forklift Operator',
    'Tool and Die Maker',
  ],
  'Transportation and Logistics': [
    'Truck Driver (Delivery or Long-Haul)',
    'Dockworker',
    'Warehouse Associate',
    'Crane Operator',
    'Freight Handler',
  ],
  'Agriculture and Farming': [
    'Farm Worker',
    'Harvester',
    'Livestock Handler',
    'Fisherman',
    'Irrigation Technician',
  ],
  'Mining and Quarrying': [
    'Miner',
    'Driller',
    'Oil Rig Worker',
    'Quarry Worker',
    'Blaster',
    'Excavation Operator',
  ],
  'Hospitality and Food Services': ['Chef/Cook', 'Dishwasher', 'Housekeeper', 'Maintenance Worker'],
  'Healthcare and Public Services': [
    'Paramedic/EMT',
    'Waste Management Worker',
    'Security Guard',
    'Maintenance Custodian',
  ],
  'Technical Trades': [
    'Auto Mechanic',
    'Aircraft Technician',
    'Appliance Repair Technician',
    'Telecommunications Technician',
  ],
  'Utilities and Infrastructure': [
    'Lineman',
    'Water Treatment Operator',
    'Road Maintenance Worker',
    'Other',
  ],
};
